name: Realese

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish 🚀
        run: npm run lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: GH Release
        uses: softprops/action-gh-release@v1
