name: Test

on:
  push:
    paths:
      - "project/**"
  pull_request:
    paths:
      - "project/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "project/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('project/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        id: test
        continue-on-error: true
        run: npm test

      - name: Uploading screenshots on failure
        if: steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots
          path: project/packages/examples/test/e2e/screenshots/

      - name: Exit signal
        if: steps.test.outcome == 'failure'
        run: exit 1
